#!/bin/bash

prev=a

while ((1))
do
	if [[ -e log.txt ]]
	then
		cur=$( tail -n 1 log.txt )
		if [[ $cur =~ ^-?[0-9]+$ ]];
		then
			echo $cur
			prev=$cur
		else
			echo "Spoiler Alert!"
			break
		fi
	fi
done
